# Site settings
title: Workflow Prototypes
author: Land Registry
email:
description: Land Registry
baseurl: "/workflow-prototypes/" # the subpath of your site, e.g. /blog/
url: "http://www.landregistryconcept.co.uk" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
